version: '3.4'

services:
  productdb:
    image: mongo

  basketdb:
    image: redis:alpine

  invoicedb: 
    image: mcr.microsoft.com/mssql/server:2017-latest

  postgresql_userdb:
    image: postgres:latest
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=adminadmin
      - POSTGRES_DB=userdb
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes: 
         - database-data:/var/lib/postgresql/data/

  pgadmin:
    image: dpage/pgadmin4
    environment: 
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    restart : unless-stopped
    volumes:
      - pgadmin:/root/.pgadmin

  userapi:
    image: ${DOCKER_REGISTRY-}userapi
    ports :
     - "1650"
    build:
      context: .
      dockerfile: User/UserApi/Dockerfile
    depends_on: 
      - postgresql_userdb

  rabbitmq:
    image: rabbitmq:3-management-alpine

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.2

  invoiceapi:
    image: ${DOCKER_REGISTRY-}invoiceapi
    build:
      context: .
      dockerfile: Invoice/InvoiceApi/Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Basket/Basket.Api/Dockerfile

  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: ReverseProxy/APIGateway/Dockerfile

  productapi:
    image: ${DOCKER_REGISTRY-}productapi
    build:
      context: .
      dockerfile: Product/ProductApi/Dockerfile

volumes:
  database-data:
  pgadmin:
  mongo_data:
  elasticsearch-data:




