version: '3.4'

services:
  
  basketdb:
    container_name: basketdb
    restart: always    
    ports:
        - "6379:6379"

  invoicedb: 
    container_name: invoicedb
    ports:
        - "433:433"
    environment:
        SA_PASSWORD: "Omar123456"
        ACCEPT_EULA: "Y"
 

  userapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
       - "8002:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  invoiceapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8003:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  
  basket.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings:ConnectionString=basketdb:6379"
    ports:
      - "8001:80"
    depends_on:
      - basketdb

