version: '3.4'

services:
  
  productdb:
    container_name: productdb
    restart: always
    ports:
        - "27017:27017"
    volumes:
        - mongo_data:/data/db

  basketdb:
    container_name: basketdb
    restart: always    
    ports:
        - "6379:6379"

  invoicedb: 
    container_name: invoicedb
    ports:
        - "433:433"
    environment:
        SA_PASSWORD: "Omar123456"
        ACCEPT_EULA: "Y"
 

  userapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
       - "8002:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  invoiceapi:
    container_name: invoiceapi
    environment:
       - ASPNETCORE_ENVIRONMENT=Development
       - "ConnectionStrings:OrderingConnectionString=Server=invoicedb;Database=InvoiceDb;User Id=sa;Password=Omar123456"            
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      - invoicedb
    ports:
      - "8003:80"

  basket.api:
    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings:ConnectionString=basketdb:6379"
    ports:
      - "8001:80"
    depends_on:
      - basketdb
  
  productapi:
    container_name: productapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://productdb:27017"
    depends_on:
      - productdb
    ports:
      - "8000:80"

  apigateway:
    container_name: apigateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - basket.api
      - productapi
      - userapi
      - invoiceapi
    ports:
      - "8010:80"

