version: '3.4'

services:

  invoicedb: 
    container_name: invoicedb
    ports:
        - "1433:1433"
    environment:
        SA_PASSWORD: "Omar123456"
        ACCEPT_EULA: "Y"
 

  userapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
       - "8002:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  invoiceapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8003:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  