version: '3.4'

services:

  postgresql_userdb:
    image: postgres:latest
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=adminadmin
      - POSTGRES_DB=userdb
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes: 
         - database-data:/var/lib/postgresql/data/

  pgadmin:
    image: dpage/pgadmin4
    environment: 
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    restart : unless-stopped
    volumes:
      - pgadmin:/root/.pgadmin

  userapi:
    image: ${DOCKER_REGISTRY-}userapi
    ports :
     - "1650"
    build:
      context: .
      dockerfile: UserApi/Dockerfile
    depends_on: 
      - postgresql_userdb
volumes:
  database-data:
  pgadmin:
